version: "3.1"

services:
  mysql:
    container_name: task-manager-mysql
    image: mysql:8.0-oracle
    restart: always
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task-manager-admin
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
